# KitPvP Config

main-world: 'world'
kill-rewards:
  message: '§6You have recieved §a%m §6for killing §4%p'
  reward-amount: 5.0
  potion-effects:
   - blindness
   - poison
   - hunger
   - weakness
   - slow
   - wither
   - confusion
launchpad:
  type: 17
  plate: STONE_PLATE
  strength: 6
  height: 2.0

# <-- Discord --> #

registration-channel: 'registration'
# Enables a bot channel where bot commands can only be used
bot-channel-enabled: false
# Deletes all messages from bot and player command message
bot-channel-delete: false
bot-channel: 'bot-commands'
bot-token:
command-prefix: '>'

